<h1> Комментарий ревьюера </h1>

Привет, Глеб!
Меня зовут Виктория Ильина, и я буду проверять твой проект. Предлагаю общаться на "ты", но если тебе будет не комфортно, обязательно сообщи и мы перейдем на "вы". 

Моя основная цель - не указать на совершённые тобой ошибки, а поделиться своим опытом и помочь тебе стать специалистом по Data Science. Ты уже проделал большую работу над проектом, но давай сделаем его ещё лучше. Ниже ты найдёшь мои комментарии - пожалуйста, не перемещай, не изменяй и не удаляй их. Я буду использовать различные цвета, чтобы было легче воспринимать мои комментарии:

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера❌:</b> Так выделены самые важные замечания. Без их отработки проект не будет принят.
</div>

<div class="alert alert-block alert-warning">
<b>Комментарий ревьюера🤔:</b> Так выделены небольшие замечания. Одно-два таких замечания в проекте допустимы, но если их будет больше - тебе будет необходимо внести исправления. Однако, если перед нами стоит цель не просто сдать проект и забыть, а приобрести новые знания и успешно применять их в будущем, я бы всё-таки рекомендовала тебе прорабатывать эти недочёты.
</div>
    
<div class="alert alert-block alert-success">
<b>Комментарий ревьюера👍:</b> Так я выделю все остальные комментарии.
</div>
    
Давай работать над проектом в диалоге: если ты что-то меняешь в проекте или отвечаешь на мои комментарии - пиши об этом. Мне будет легче отследить изменения, если ты выделишь свои комментарии:

<div class="alert alert-block alert-info">
<b>Комментарий студента:</b> Например, вот так.
</div>

Давай посмотрим, что получилось!

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split


In [2]:
data=pd.read_csv('/datasets/insurance.csv')
data['Возраст'] = pd.to_numeric(data['Возраст'], downcast='integer')
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   int8   
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(1), int64(3), int8(1)
memory usage: 161.3 KB


In [3]:
def check_data (data_i):
    temp = data_i.copy() 
   
    list_c=data_i.columns
    for col_l in list_c:
        print('-------------------------')
        #print(col_l, temp[col_l].sort_values().unique())
        print(col_l,'|кол-во строк',len(temp),'| кол-во NaN',temp[col_l].isna().sum(),
        '| процент NaN', round(temp[col_l].isna().sum()/len(temp)*100, 2),'%')

In [4]:
check_data(data)

-------------------------
Пол |кол-во строк 5000 | кол-во NaN 0 | процент NaN 0.0 %
-------------------------
Возраст |кол-во строк 5000 | кол-во NaN 0 | процент NaN 0.0 %
-------------------------
Зарплата |кол-во строк 5000 | кол-во NaN 0 | процент NaN 0.0 %
-------------------------
Члены семьи |кол-во строк 5000 | кол-во NaN 0 | процент NaN 0.0 %
-------------------------
Страховые выплаты |кол-во строк 5000 | кол-во NaN 0 | процент NaN 0.0 %


In [5]:

features = data.drop('Страховые выплаты', axis=1)
target = data['Страховые выплаты']
print(features.head())
print()
print(target.head())

   Пол  Возраст  Зарплата  Члены семьи
0    1       41   49600.0            1
1    0       46   38000.0            1
2    0       29   21000.0            0
3    0       21   41700.0            2
4    1       28   26100.0            0

0    0
1    1
2    0
3    0
4    0
Name: Страховые выплаты, dtype: int64


**Вывод:** Загруженные данные не имеют дефектов, пропусков, кол-во строк совпадает для каждого признака.  
    Изменен тип данных у поля "Возраст"


<div class="alert alert-block alert-warning">
<b>Комментарий ревьюера🤔:</b> Отсутствует промежуточный вывод и твои комментарии по поводу данных
</div>
<div class="alert alert-block alert-info">
<b>Комментарий студента:</b> Вывод добавлен.
</div>

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера V.2👍:</b> Принято
</div>

## Умножение матриц

In [6]:
X = np.concatenate((np.ones((features.shape[0], 1)), features), axis=1)
y = target
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
display(w[1:])
model = LinearRegression()
model.fit(features, target)
model.coef_


array([ 7.92580543e-03,  3.57083050e-02, -1.70080492e-07, -1.35676623e-02])

array([ 7.92580543e-03,  3.57083050e-02, -1.70080492e-07, -1.35676623e-02])

In [7]:
prediction=model.predict(features)
print(r2_score(target, prediction))

0.4249455028666801


В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Вопрос:** Измениться ли коф.R2 линейной регрессии при умножение матрицы признаков на обратимую квадратную матрицу?

**Ответ:** Нет

**Обоснование:** 
$$a = Xw$$

$$a1=XPw$$

$$a1=XP((XP)^T XP)^{-1} (XP)^T y$$
воспользуемся правилом:$$ (A B)^T=B^TA^T$$

$$a1=XP(P^TX^TXP)^{-1} P^TX^T y=XP(P^T(X^TX)P)^{-1} P^TX^T y$$

воспользуемся правилом:$$ (A B)^{-1}=B^{-1}A^{-1}$$

$$a1=XPP^{-1}(X^TX)^{-1}(P^T)^{-1} P^TX^T y$$
$$a1=XE(X^TX)^{-1}EX^T y=X(X^TX)^{-1}X^T y=a$$



**Вывод** Значение a не меняется при умножение мартицы на обратимую

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера❌:</b> Тут нужно привести теоретическое обоснование неизменности качества регрессии с помощью формул или очень подробно словами
</div>
<div class="alert alert-block alert-info">
<b>Комментарий студента:</b> Добавил  теоритическое обоснование.
</div>

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера V.2❌:</b> К сожалению, у тебя допущена ошибка в доказательстве, так как для неквадратных матриц $X$ и $X^T$ обратных матриц не существует, то мы не можем раскрывать $(X^T X)^{-1}$
    
Теория по обратным матрицам: https://www.berdov.com/works/matrix/obratnaya-matrica/ 
</div>


<div class="alert alert-block alert-success">
<b>Комментарий ревьюера V.3👍:</b> Теперь верно =)
</div>

## Алгоритм преобразования

**Алгоритм**

1) Умножаем матрицу признаков на обратимую матрицу  
2) Умножаем на 100  
3) Вычитаем 30


**Обоснование**

На линейную регрессию не влияют операции, связанные с умножение/делению/вычитанием/сложением матрицы признаков на число, а также умножение на обратимую квадратную матрицу.

In [43]:
def change_features(features):
    n = features.shape[1]
    np.random.seed(1234567)
    random_matrix = np.random.randint(1,5,(n,n))
    
    print(random_matrix)
    
    if (np.linalg.matrix_rank(random_matrix) < n):
        print ("Not invertible!")
    else:
        print ("Invertible!")

    
    return ((features @random_matrix)*100)-30

In [44]:

features_new=change_features(features)
features_train, features_test, target_train, target_test = train_test_split( features_new, target, test_size=0.25, random_state=1234567)
model = LinearRegression()
model.fit(features_train, target_train)
print("R2",r2_score(target_test, model.predict(features_test)))

[[4 4 1 3]
 [2 3 1 2]
 [1 2 3 3]
 [4 4 2 1]]
Invertible!
R2 0.41295701079948577


In [16]:
P = np.random.rand(4,4)
np.linalg.inv(P)
features_new  =features@
print(features.head())
print(features_new.head())

   Пол  Возраст  Зарплата  Члены семьи
0    1       41   49600.0            1
1    0       46   38000.0            1
2    0       29   21000.0            0
3    0       21   41700.0            2
4    1       28   26100.0            0
             0             1             2           3
0  4196.713775  27629.444036  26050.067978  292.111222
1  3216.708755  21179.980598  19971.513603  227.185517
2  1777.712954  11707.408825  11040.199930  126.146795
3  3527.011794  23217.979522  21887.581251  242.104494
4  2209.015198  14544.066183  13714.243574  155.445955


## Проверка алгоритма

In [45]:

features_train, features_test, target_train, target_test = train_test_split( features, target, test_size=0.25, random_state=1234567)
model = LinearRegression()
model.fit(features_train, target_train)
print("R2",r2_score(target_test, model.predict(features_test)))

R2 0.4129570107995183


**Вывод:** Показатель качества лин.регрессии R2 не изменился после применения алгоритма шифрования данных. 

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера👍:</b> Верно, таким образом в случае домножения матрицы признаков на случайную обратимую матрицу можно обеспечить защиту данных, не особо потеряв в качестве модели. (Незначительное отличие вызвано особенностью преобразования матриц и чисел с плавающей точкой, это норма)
</div>


## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [ ]  Весь код выполняется без ошибок
- [ ]  Ячейки с кодом расположены в порядке исполнения
- [Х]  Выполнен шаг 1: данные загружены
- []  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [ ]  Указан правильный вариант ответа
    - [ ]  Вариант обоснован
- [ ]  Выполнен шаг 3: предложен алгоритм преобразования
    - [Х]  Алгоритм описан
    - [Х]  Алгоритм обоснован
- [Х]  Выполнен шаг 4: алгоритм проверен
    - [Х]  Алгоритм реализован
    - [Х]  Проведено сравнение качества моделей до и после преобразования

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера❌:</b> Спасибо тебе за проделанную работу, к сожалению, сейчас я не могу принять твой проект, поэтому тебе придётся ещё немного поработать:
    
- добавь промежуточный вывод и твои комментарии по поводу данных;
- распиши доказательство.
    
До скорой встречи, если у тебя есть ещё какие-то вопросы или ты хочешь какую-то подборку статей, то обязательно пиши =)
</div>

<div class="alert alert-block alert-success">
<b>Комментарий ревьюера V.2👍:</b> Дополнительные материалы:
        
Обзоры по применению криптографии в машинном обучении: https://arxiv.org/pdf/1902.04109.pdf, https://www.researchgate.net/publication/342746786_Some_Applications_of_Machine_Learning_in_Cryptography

Небольшой обзор на Шифр Хилла: https://habr.com/ru/post/595281/
   
Примеры использования линейной алгебры в машинном обучении:
https://machinelearningmastery.com/examples-of-linear-algebra-in-machine-learning/
    
Для чего нужна математика в машинном обучении?
https://proglib.io/p/dlya-chego-nuzhen-matematicheskiy-analiz-v-mashinnom-obuchenii-2021-02-15

Большая статья по векторам:
https://neptune.ai/blog/understanding-vectors-from-a-machine-learning-perspective  

Можно ещё дополнительно посмотреть лекции от МФТИ https://www.youtube.com/playlist?list=PLk4h7dmY2eYHHTyfLyrl7HmP-H3mMAW08
    
Классная серия роликов по линейной алгебре на английском (можно включить автоматические русские субтитры): https://www.youtube.com/playlist?list=PLRDl2inPrWQW1QSWhBU0ki-jq_uElkh2a

Удачи в будущих проектах и работе =)
</div>